name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false
