name: release

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '24'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          runtime: 'node@${{ env.NODE_VERSION }}'
          cache: true

      - run: pnpm run build

      - name: Pack npm tarball
        run: npm pack ./dist/ngx-pdf-viewer

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false
          files: '*.tgz'
